# GitHub Sponsors configuration
# These links power the "Sponsor" button on GitHub

# GitHub Sponsors username
github: brennanbrown

# Ko-fi username (without the domain)
ko_fi: brennan

# Additional custom sponsorship URLs (array)
custom:
  - https://ko-fi.com/brennan
