# Netlify configuration for the Foothills demo
# Site will publish the repository root, and redirect "/" to the preview page.

[build]
  # Static site: no build command required
  command = ""
  publish = "."

# Redirect root to preview for a nicer demo URL
[[redirects]]
  from = "/"
  to = "/preview/"
  status = 301
  force = true

# Basic caching for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
